from datetime import datetime


class InterfaceBackend:
    def api_sync(self, begin: datetime, end: datetime): ...

    def api_update(self, begin: datetime, end: datetime, wxids: list[str]): ...

    def api_render(self, begin: datetime, end: datetime, wxids: list[str]): ...

    def api_test(self, *args, **kwargs): ...

    def update_info(self, info: dict): ...


class InterfaceFront:

    def emit_test_processing(self, value: int): ...

    def emit_info_update(self, info: dict): ...
